#!/bin/bash


case $1 in
	open | o)
		spotify
		;;
        play | pl)
		dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Play
		;;
        pause | pa)
		dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Pause
                ;;
	trigger | t)
		dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause
		;;
        next | n)
                dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next
                ;;
	previous | pr)
		dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous
		;;
	setvolume | sv)
		amixer -D pulse sset Master $2%
		;;
	mute | m)
		amixer -D pulse sset Master 0
		;;
	volumeup | vu)
		amixer -D pulse sset Master $2%+
		;;
	volumedown | vd)
		amixer -D pulse sset Master $2%-
                ;;
	*)
		echo "Find what you want"
		echo "help"
		;; 
esac
